config/routes.rb
SBerryCake::Application.routes.draw do
  devise_for :busses
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'index#index'

end

app/models/buss.rb
class Buss < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
		 :omniauthable, :omniauth_providers => [:facebook]
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :name
  
  # attr_accessible :title, :body

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
  end
  user
end


def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fb_controller.rb
class FbController < ApplicationController
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fb_helper.rb
module FbHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/fb/channel.html.erb
<script src="//connect.facebook.net/en_US/all.js"></script>

app/views/index/fbtest.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : 'YOUR_APP_ID', // App ID from the App Dashboard
      channelUrl : '//localhost:3000/channel.html', // Channel File for x-domain communication
      status     : true, // check the login status upon init?
      cookie     : true, // set sessions cookies to allow your server to access the session?
      xfbml      : true  // parse XFBML tags on this page?
    });

    // Additional initialization code such as adding Event Listeners goes here

  };

  // Load the SDK's source Asynchronously
  // Note that the debug version is being actively developed and might 
  // contain some type checks that are overly strict. 
  // Please report such bugs using the bugs tool.
  (function(d, s, id, debug){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk', /*debug*/ false));
</script>

app/views/index/index.html.erb
<% provide(:title, 'Home') %>

<h1> Welcome to sBerryCake Alpha </h1>

<a href=<%=new_user_registration_path%>  class="btn btn-large btn-primary" >  Promoter Sign Up</a>

<a href=<%=new_buss_registration_path%>  class="btn btn-large btn-primary" >  Business Sign Up</a>

<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Made by Jeffrey Tong
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
      <li><a href="http://www.jefftong.net/">Me</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
    	<nav>
    	<ul class="nav nav-pills pull-right">
		<% if user_signed_in? %>
			<Logged in as <strong><%= current_user.email %></strong>.
			<li><%= link_to 'Edit profile', edit_user_registration_path %> </li>
			<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
		<% else %>
			<li><%= link_to "Login", new_user_session_path %></li>
		<% end %>
		</ul>
	</nav>
</div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>sBerryCake | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
	    <% flash.each do |name, msg| %>
	    	<%= content_tag :div, msg, id: "flash_#{name}", class: "alert alert-#{name}" %>
		<% end %>
		<%= @name %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>